package com.example.cs5610f20serverjavahualinbai.services;

import com.example.cs5610f20serverjavahualinbai.models.Widget;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


public class WidgetService {

  // hardcode a local list of widgets to simulate a database
  List<Widget> widgets = new ArrayList<>();
//  {
//
//    widgets.add(new Widget("123", "Widget 123", "HEADING", "5f90dca2895b1e0017f05dec"));
//    widgets.add(new Widget("234", "Widget 234", "PARAGRAPH", "5f90dca5895b1e0017f05ded"));
//    // third widget belongs to some other topic
//    widgets.add(new Widget("345", "Widget 345", "HEADING", "5f90dca5895b1e0017f05ded"));
//
//  }


  // @GetMapping("/find/all/widgets") // bad url
  // add token api to tell that this is not physical directory structure
  // but an api meant for dynamic data access
  public List<Widget> findAllWidgets() {
    return widgets;
  }


  public List<Widget> findWidgetsForTopic(String topicId) {
    // ws: widgets for a particular topic
    List<Widget> ws = new ArrayList<>();
    for (Widget w : widgets) {
      if (w.getTopicId().equals(topicId)) {
        ws.add(w);
      }
    }
    return ws;
  }


  // reference the path param, parse it and convert to String, and then pass to widgetId
  public Widget findWidgetById(String widgetId) {
    for (Widget w : widgets) {
      if (w.getId().equals(widgetId)) {
        return w;
      }
    }
    return null;
  }

  // listen to incoming POST request
  // the RequestBody represents the body parsed from the request
  // parse JSON from the body of HTTP request coming from client
  // then the RequestBody tries to create an instance of type widget and
  // map the properties specified by client to the properties of widget
  // expect the parsed JSON object also has the same set of properties (id, name, type)
  // except id is not passed to widget since it is generated by database
  public Widget createWidget(Widget widget) {
    // simulate the fact that id used as primary key is set by database
    widget.setId(new Date().toString());
    // supposedly would be an insert into database
    widgets.add(widget);
    // return the actual object inserted to database
    return widget;
  }


  // TODO: updateWidget, deleteWidget
  // widgetId is populated with the path var from incoming HTTP request
  // newWidget is populated with the new object from incoming HTTP request
  public Integer updateWidget(
      String widgetId,
      Widget newWidget) {
    for (Widget w : widgets) {
      if (w.getId().equals(widgetId)) {
        w.setName(newWidget.getName());
        w.setType(newWidget.getType());
        w.setText(newWidget.getText());
        w.setSize(newWidget.getSize());
        return 1;
      }
    }
    return 0; // return an int status
  }


  public Integer deleteWidget(String widgetId) {
    for (Widget w : widgets) {
      if (w.getId().equals(widgetId)) {
        widgets.remove(w);
        return 1;
      }
    }
    return 0;
  }


}
